### ISSUE TITLE
[Fix] 할 일 도메인 API 연동 중 발생한 오류 수정

### ISSUE THREAD

**Issue by soun997** [let-s-record-it/Server#114]
## Description
할 일 도메인 API 연동 중 발생한 오류를 수정한다.

## Todo
- [x] `relatedMonthlyGoalId`가 null일 때 발생하는 예외 처리
- [x] null 대신 `Optional` 반환하도록 수정
- [x] 테스트 코드 리팩토링
