### ISSUE TITLE
[Feature] 선택 할 일 이후 할 일 전체 삭제 기능, 선택 할 일 단일 삭제 기능 구현

### ISSUE THREAD

**Issue by soun997** [let-s-record-it/Server#176]
## Description
- 선택 할 일 이후 할 일을 전체 삭제하는 기능을 구현한다.
- 선택 할 일을 삭제하는 기능을 구현한다.

## Todo
- [x] 선택 할 일 이후 할 일 전체 삭제 기능 구현
- [x] 선택 할 일 이후 할 일 전체 삭제 기능 테스트
- [x] 선택 할 일 삭제 기능 구현
- [x] 선택 할 일 삭제 기능 테스트
