### ISSUE TITLE
[Fix] 월 목표 조회 조건에 `deleted` 컬럼 포함

### ISSUE THREAD

**Issue by soun997** [let-s-record-it/Server#38]
## Description
soft delete 정책을 적용하기로 했기 때문에 조회 조건에 `deleted` 컬럼을 추가한다.

## Todo
- [x] 월 목표 수정 query 변경
- [x] 월 목표 목록 조회 query 변경
- [x] 월 목표 상세 조회 query 변경
