### ISSUE TITLE
[Feature] 할 일 엔티티 구현

### ISSUE THREAD

**Issue by soun997** [let-s-record-it/Server#88]
## Description
`Task` 엔티티를 구현한다.

## Todo
- [x] `Task` 엔티티 구현
- [x] `TaskRepetition` 엔티티 구현
- [x] `WeeklyGoal` 엔티티 구현 (`TaskGroup`과의 연관관계 때문)
